### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by d-g-h** [addyosmani/oust#15]
Upgrade to Cheerio to 0.19.0 to squash WARN for this repo, and any that depend on it (critical)
```sh
❯ npm install critical
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
```

**Comment by PiyushMishra318** [comment]
This update still gives me vulnerabilities with "css-what".
![image](https://user-images.githubusercontent.com/42195216/123392077-48fb6380-d5ba-11eb-8436-9d272bdc522c.png)

I don't know if it can just directly be updated to the latest critical version but I'll make a PR with the updated version.
